services:
  app:
    image: node:lts-alpine
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    stdin_open: true
    working_dir: /app
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=example
      - MYSQL_USER=example
      - MYSQL_PASSWORD=example
    depends_on:
      - db
    command: sh -c "npm install && npm run dev"

  db:
    image: mariadb:10.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW --expire-logs-days=2
    volumes:
      - ~/data/mysql:/var/lib/mysq
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_PASSWORD: example
      MYSQL_DATABASE: example
      MYSQL_USER: example

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:80'
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - db
