services:
  app:
    image: node:lts-alpine
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    stdin_open: true
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=example
      - MYSQL_USER=example
      - MYSQL_PASSWORD=example
    depends_on:
      - db

  db:
    image: mariadb:10.6
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_PASSWORD: example
      MYSQL_DATABASE: example
      MYSQL_USER: example

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:80'
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - db
