services:
  app:
    image: node:lts-alpine
    container_name: docker-next
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
    working_dir: /app
    command: sh -c "npm install && npm run dev"

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - ~/data/mongoDB:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    command: mongod --logpath /var/log/mongodb/mongod.log --logappend --logRotate rename
