services:
  app:
    image: node:lts-alpine  # Bruger et færdigbygget image fra Docker Hub
    container_name: docker-next
    ports:
      - '3000:3000'
    volumes:
      - .:/app  # Mapping af dit app-directory fra værtsmaskinen til containeren
      - /app/node_modules  # Gemmer node_modules for at undgå geninstallation hver gang
    depends_on:
      - mongo
    working_dir: /app  # Arbejdsdirectory i containeren
    command: sh -c "npm install && npm run dev"  # Kommando til at installere afhængigheder og starte appen

  mongo:
    image: mongo  # Bruger et færdigbygget image fra Docker Hub
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - ~/data/mongoDB:/data/db  # Mount til at gemme MongoDB data på værtsmaskinen
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    command: mongod --logpath /var/log/mongodb/mongod.log --logappend --bind_ip_all  # Ekstra kommando til at specificere MongoDB-logfiler
